import type { Metadata } from "next";
import { Open_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-open-sans",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair",
  display: "swap",
});
import Footer from "@/components/ui/Footer";
import { CartProvider } from "@/app/context/CartContext";
import { CatalogProvider } from "@/app/context/CatalogContext";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "To the moon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${playfair.variable} ${openSans.className} min-h-screen font-sans`}>

        <CatalogProvider>
          <CartProvider>{children}</CartProvider>
        </CatalogProvider>

        {/* Footer */}
        <Footer />
        <Toaster position="bottom-right" />

      </body>
    </html>
  );
}
