import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/ui/Footer";
import { CartProvider } from "@/app/context/CartContext";

export const metadata: Metadata = {
  title: "To the moon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-700 min-h-screen text-gray-800">

        <CartProvider>{children}</CartProvider>

        {/* Footer */}
        <Footer />

      </body>
    </html>
  );
}
